### ISSUE TITLE
Change text that appears on "Reset Everything" button press

### ISSUE THREAD

**Issue by m-lara** [anthonyisensee/incidenttracker#10]
Can the "Reset Everything" text that comes up in the windows when that button is pressed read something else? For example instead of "Do you wish to reset local storage?" (I mean really, what's that mean anyway?) to something like "Do you wish to clear all incidents that are being tracked? This action can't be undone."

**Comment by anthonyisensee** [comment]
Incident Tracker will be deprecated in favor of the new [Event Tracker](https://eventtracker.anthonyisensee.com/) application. This feature request has been linked to the outstanding [Event Tracker issue to add a big red delete button](https://github.com/anthonyisensee/event-tracker/issues/16).
