### ISSUE TITLE
Add a toggle for light/dark Mode

### ISSUE THREAD

**Issue by m-lara** [anthonyisensee/incidenttracker#7]
Sometimes I just want the light in the dark (or dark in the light) and I'd like to toggle when I get it!

**Comment by anthonyisensee** [comment]
Note to self: https://bulma.io/documentation/features/dark-mode/

To force dark mode on a full page use:
```html
<html data-theme="dark">
<!-- Or -->
<html class="theme-dark">
```

**Comment by anthonyisensee** [comment]
@m-lara you will be delighted to know that this has now been completed. You may now sear your retinas whenever you so desire.

There may or may not be an easter egg in the console when using this feature while your browser default is dark mode. 😁

**Comment by anthonyisensee** [comment]
@m-lara this has also been added to event tracker via https://github.com/anthonyisensee/event-tracker/commit/53c8e67cc0edbcce6c3f1592af11f6953062813d.
