### ISSUE TITLE
switching between incidents currently running incidents

### ISSUE THREAD

**Issue by m-lara** [anthonyisensee/incidenttracker#9]
When I start a new incident, I don't see how I can switch back to a previous incident to see how much time has passed on it, unless I do manual calculations (which I won't do because I'm too lazy) from the general list of incidents. So it forces me to keep a browser window open for each incident and that's just too messy.

**Comment by anthonyisensee** [comment]
Please see this [response on another issue](https://github.com/anthonyisensee/incidenttracker/issues/8#issuecomment-2359837703).
